### ISSUE TITLE
Strange artifact in the middle of my name & break in wrong place

### ISSUE THREAD

**Issue by itsthejoker** [scastiel/github-business-card#3]
Hi, Sébastien! This is very cool project. I am having two issues when trying it out:

Here's the generated output: 
![image](https://user-images.githubusercontent.com/5179553/201537827-e9f8a865-4752-4c90-be33-e6fd70779546.png)

Issue 1: there's an odd graphical glitch at the end of "Joe"

Issue 2: in the description, the break should be at `@grafeasgroup` instead of `@\ngrafeasgroup`.

**Comment by scastiel** [comment]
Hi Joe! It looks like you do have an invisible character in your name, even on GitHub. Here is what it looks like in the Chrome DevTools (on github.com):

<img width="377" alt="Screen Shot 2022-11-16 at 16 13 49" src="https://user-images.githubusercontent.com/301948/202295787-2385e66a-cbf7-432e-9765-36a41ec2b44d.png">

You should probably edit your full name in your GitHub account to fix it 😉

**Comment by itsthejoker** [comment]
Well that's entirely on me. Whoops. Will close now 😅
